# 引入公共配置
spring:
  config:
    import: classpath:application-common.yml

  application:
    name: payment-service
    database-name: payment_db

  # Kafka 配置（额外配置，补充共享配置）
  kafka:
    consumer:
      group-id: payment-service-group
    listener:
      ack-mode: manual

  # Nacos 服务特定配置
  cloud:
    nacos:
      config:
        shared-configs:
          - data-id: shared-config.yml
            refresh: true

# 服务端口
server:
  port: 8085

# OpenTelemetry 服务名（覆盖公共配置）
otel:
  service:
    name: ${spring.application.name}
