# 引入公共配置
spring:
  config:
    import: classpath:application-common.yml

  application:
    name: user-service
    database-name: user_db

  # MySQL 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${spring.application.database-name}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8mb4
    username: root
    password: root

  # JPA 服务特定配置
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # Nacos 服务特定配置
  cloud:
    nacos:
      config:
        shared-configs:
          - data-id: shared-config.yml
            group: DEFAULT_GROUP
            refresh: true

# 服务端口
server:
  port: 8081

# OpenTelemetry 服务名（覆盖公共配置）
otel:
  service:
    name: ${spring.application.name}
